server:
  port: 9000
  zone: Ukraine

retry-config:
  maxAttempts: 3
  maxDuration: 30000
  delay: 3000
load:
  balancer:
    servers:
      - id: primary
        url: http://localhost:8080
        zone: Ukraine
        enabled: true
      - id: slave
        url: http://localhost:8085
        zone: West-Europe
        enabled: true