server:
  port: 9000
  zone: Ukraine
load:
  balancer:
    book: http://localhost:8900/

#load:
#  balancer:
#    type: random
#    servers:
#      - id: primary
#        url: http://localhost:8080
#        zone: Ukraine
#        enabled: true
#      - id: slave
#        url: http://localhost:8085
#        zone: West-Europe
#        enabled: true