server:
  port: 9000
  zone: Ukraine

load:
  balancer:
    servers:
      - id: primary
        url: http://localhost:8080
        zone: Ukraine
        enabled: true
      - id: slave
        url: http://localhost:8085
        zone: West-Europe
        enabled: true